apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demi

resources:
  - ../../base

images:
  - name: ghcr.io/chigen/demi-container-final-assignment/inventory-service
    newTag: latest
  - name: ghcr.io/chigen/demi-container-final-assignment/order-service
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: inventory-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: order-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3 
