server:
  port: 8080

spring:
  application:
    name: order-service
  
  # H2 In-Memory Database Configuration
  datasource:
    url: jdbc:h2:mem:order_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console (for debugging - optional)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop  
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true  
  
  # SQL initialization
  sql:
    init:
      mode: always  
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Service communication configuration
inventory:
  service:
    url: http://localhost:8081

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: FULL

logging:
  level:
    com.example.orderservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
