apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-processing-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/${GITHUB_REPOSITORY}.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: demi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
