apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-processing-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chigen/demi-container-final-assignment.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: demi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# argocd
# Admin
# C1DsKmPq90SXH-WV 
