server:
  port: 8081

spring:
  application:
    name: inventory-service
  
  # H2 In-Memory Database Configuration
  datasource:
    url: jdbc:h2:mem:inventory_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console (for debugging - optional)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # 每次启动重新创建表结构
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true  # 延迟数据源初始化，确保表创建后再插入数据
  
  # SQL initialization
  sql:
    init:
      mode: always  # 总是执行初始化脚本
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.inventoryservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
