apiVersion: v1
kind: Secret
metadata:
  name: ghcr-token
  namespace: demi
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7fX19
---
# This Secret contains a minimal docker config for public images
# For private images, you need to:
# 1. Create GitHub Personal Access Token (PAT) with packages:read permission
# 2. Generate docker config json:
#    echo -n '{"auths":{"ghcr.io":{"auth":"'$(echo -n "username:token" | base64)'"}}}' | base64
# 3. Replace the .dockerconfigjson value with the generated base64 string
# 4. Or use kubectl command to create:
#    kubectl create secret docker-registry ghcr-token \
#      --docker-server=ghcr.io \
#      --docker-username=YOUR_GITHUB_USERNAME \
#      --docker-password=YOUR_GITHUB_TOKEN \
#      --namespace=demi 
