apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order-processing-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: order-service 
