apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: demi
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ghcr.io/chigen/demi-container-final-assignment/order-service:3f60fa72484f2fb4f10a7ad5eaac63e4c530f82b
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SERVICE_INVENTORY_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: service.inventory.url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5 
